config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , registrations: "users/registrations", sessions: 'users/sessions'}

  root 'welcome#index'

  resources :users, controller: 'users', only: [:show, :edit, :update, :destroy, :index] 
  
  resources :items do
    resources :rentals, :only => [:create, :new, :show]
  end
  
   get "/items/tags/:tag_id" => "items#tag", as: "tags"
   get '/search', to: 'items#search'

  get "mailboxes/inbox" => "mailboxes#inbox", as: :mailboxes_inbox
  get "mailboxes/sent" => "mailboxes#sent", as: :mailboxes_sent
  get "mailboxes/archive" => "mailboxes#archive", as: :mailboxes_archive

  resources :conversations do
    member do
      post :reply
      post :archive
      post :unarchive
    end
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	  before_action :authenticate_user!

  def new
  	@item = Item.find(params[:item_id])
  end
  
  
  def create
    @item = Item.find(params[:conversation][:item_id])
    recipients = User.where(id: conversation_params[:user_id])

    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message was successfully sent!"
    redirect_to item_path(@item.id)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def archive
    conversation.move_to_trash(current_user)
    redirect_to mailboxes_inbox_path
  end

  def unarchive
    conversation.untrash(current_user)
    redirect_to mailboxes_inbox_path
  end

  private

  def conversation_params
    params.require(:conversation).permit(:user_id, :item_id, :title, :subject, :body,recipients:[])
  end
  
    def message_params
    params.require(:message).permit(:body, :subject)
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="<%= user_path(conversation.originator) %>">
      <% if conversation.originator.avatar.thumb.url %>
      <img class="media-object" src=<%= conversation.originator.avatar.thumb.url %> alt="...">
      <% end %>
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.full_name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <b><%= truncate conversation.messages.last.body, length: 145 %></b>
    <%= link_to "View", conversation_path(conversation), class: 'btn btn-info pull-right' %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.hidden_field :user_id, value:"#{@item.user_id}" %>
      <%= f.hidden_field :item_id, value:"#{@item.id}"%>
    </div>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :subject, value:"#{@item.title}", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>
    <%= f.submit "Send Message", class: "btn btn-success" %>
<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <!-- user avators can go here -->
        <% if message.sender.avatar.thumb.url %>
        <a href="<%= user_path(message.sender) %>">
          <img class="media-object" src=<%= message.sender.avatar.thumb.url %> alt="...">
        </a>
        <% end %>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.full_name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <b><%= message.body %></b>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<div class="container">
<%= render partial: 'mailboxes/folder_view', locals: { is_conversation: true } %>
</div>

app/views/conversations/show.html.erb
<div class="container">
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailboxes/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>

            <% if conversation.is_trashed?(current_user) %>
              <%= link_to 'Unarchive', unarchive_conversation_path(conversation), class: 'btn btn-info pull-left', method: :post %>
            <% else %>
              <%= link_to 'Move to Archive', archive_conversation_path(conversation), class: 'btn btn-danger pull-left', method: :post,
                    data: {confirm: 'Are you sure?'} %>
            <% end %>

            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>

</div>