config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , registrations: "users/registrations", sessions: 'users/sessions'}

  root 'welcome#index'

  resources :users, controller: 'users', only: [:show, :edit, :update, :destroy, :index] 
  
  resources :items do
    resources :rentals, :only => [:create, :new, :show]
  end
  
   get "/items/tags/:tag_id" => "items#tag", as: "tags"
   get '/search', to: 'items#search'

  get "mailboxes/inbox" => "mailboxes#inbox", as: :mailboxes_inbox
  get "mailboxes/sent" => "mailboxes#sent", as: :mailboxes_sent
  get "mailboxes/archive" => "mailboxes#archive", as: :mailboxes_archive

  resources :conversations do
    member do
      post :reply
      post :archive
      post :unarchive
    end
  end

end

app/controllers/mailboxes_controller.rb
class MailboxesController < ApplicationController
	before_action :authenticate_user!

  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def archive
    @archive = mailbox.trash
    @active = :archive
  end
end

app/helpers/mailboxes_helper.rb
module MailboxesHelper
	  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/views/mailboxes/_folder_view.html.erb
<div id="mailboxes">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailboxes/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if is_conversation %>
            <%= render 'conversations/form' %>
        <% else %>
            <%= render partial: 'conversations/conversation', collection: messages %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/mailboxes/_folders.html.erb
<ul class="list-inline">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailboxes_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span>Inbox</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailboxes_sent_path do %>
        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span>Sent</span>
    <% end %>
  </li>

  <li class="<%= active_page(:archive) %>">
    <%= link_to mailboxes_archive_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span>Archive</span>
    <% end %>
  </li>
</ul>

app/views/mailboxes/archive.html.erb
<%= render partial: 'mailboxes/folder_view', locals: { is_conversation: false, messages: @archive } %>

app/views/mailboxes/inbox.html.erb
<%= render partial: 'mailboxes/folder_view', locals: { is_conversation: false, messages: @inbox } %>

app/views/mailboxes/sent.html.erb
<%= render partial: 'mailboxes/folder_view', locals: { is_conversation: false, messages: @sent } %>