config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , registrations: "users/registrations", sessions: 'users/sessions'}

  root 'welcome#index'

  resources :users, controller: 'users', only: [:show, :edit, :update, :destroy, :index] 
  
  resources :items do
    resources :rentals, :only => [:create, :new, :show]
  end
  
   get "/items/tags/:tag_id" => "items#tag", as: "tags"
   get '/search', to: 'items#search'

  get "mailboxes/inbox" => "mailboxes#inbox", as: :mailboxes_inbox
  get "mailboxes/sent" => "mailboxes#sent", as: :mailboxes_sent
  get "mailboxes/archive" => "mailboxes#archive", as: :mailboxes_archive

  resources :conversations do
    member do
      post :reply
      post :archive
      post :unarchive
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader

	belongs_to :user
	has_many :rentals

		def disabledDates
	  i_id = self.id
  	rental = Rental.where("item_id = ?", i_id)
  	booked_days = []  	

  	rental.each do |r|
  		booked_array = *(r.start_date..r.end_date)  
			booked_days << booked_array 	 
		end
	  	booked_dates = []
	  	booked_days = booked_days.flatten
	  	booked_days.each do |b|
			booked_dates<<b.strftime("%d/%m/%Y")	  		
	  	end
	  	return booked_dates
	end

# end
	acts_as_taggable # Alias for acts_as_taggable_on :tags
	searchkick match: :word_start, searchable: [:title, :description]

	def search_card
		if self.avatar.medium.url
			avatar=self.avatar.medium.url
			return '<a href="/items/'+self.id.to_s+'">'+self.title+' $'+self.price_per_day.to_s+'<img style="max-width: 50px; max-height: 50px"src='+avatar+'></a><br>'+self.description
		else
			return '<a href="/items/'+self.id.to_s+'">'+self.title+' $'+self.price_per_day.to_s+'</a><br>'+self.description
		end
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :set_item, only: [:update, :edit, :destroy]
  
  def index
    @error=[]
    @index_page = true 
  	@item = Item.all
    if signed_in?
      items_per_page = 10  
      params[:page] = 1 unless params[:page] 
      first_item ||= (params[:page].to_i - 1) * items_per_page


    if params[:formatted_address] == "" or params[:formatted_address]==nil
      areaitems=Item.all
    else
      areaitems=[]
      
      if params[:range].to_i>0
        users=User.near(params[:formatted_address], params[:range])
      else
        if params[:postal_code] == ""
          if params[:locality] == ""
            if params[:administrative_area_level_1] == ""
                users=User.where(country: params[:country])
            else
              users=User.where(administrative_area_level_1: params[:administrative_area_level_1])
            end
          else
            users=User.where(locality: params[:locality])
          end
        else
          users=User.where(postal_code: params[:postal_code])
        end
      end

      if users==[] or users==nil
        users=User.all
        @error << "No items found in your search area. All locations displayed"
      end

      # params[:range] = "20" unless (params[:range].to_i>0)
      # users=User.near(params[:formatted_address], params[:range])
      users.each do |u|
        areaitems<<u.items
      end
      areaitems.flatten!
    end



    searchitems = Item.search(params[:term], fields: ["title", "description"], mispellings: {below: 5})
    if searchitems.blank?
      @error << "No items found in this search phrase, all items displayed"
      items=areaitems
    else
      items=areaitems&searchitems
    #   render :index
    # else
    #   render :index
    end

    


      @nb_pages_needed = items.count / items_per_page
      @nb_pages_needed+=1 if items.count / items_per_page > 0
      if params[:tag]
        @item=[]
        items.each do |i|
          @item<<i if i.tag_list.include?(params[:tag])
        end
      else    
        @item = items[first_item...(first_item + items_per_page)]
      end


      @hash = Gmaps4rails.build_markers(@item) do |item, marker|
          marker.lat item.user.latitude
          marker.lng item.user.longitude
          marker.json({:id => item.id })
          marker.json({:title => item.title })
          marker.infowindow item.search_card
          marker.picture({
           "url" => "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
           "width" =>  32,
           "height" => 32})
      end





    else
      flash[:notice] = "Please Log In or Sign Up"
      redirect_to root_path
    end
  end

  # def search
  #       @items = item.search(params[:term], fields: ["title", "location","description"], mispellings: {below: 5})
  #       if @items.blank?
  #         redirect_to items_path, flash:{danger: "no successful search result"}
  #       else
  #         render :index
  #       end
  # end  

  def new
    @item = Item.new
  end

  def create
    
    @item = current_user.items.new(item_params)  
      respond_to do |format|        
        if @item.save
          # I want to send an e-mail and then...
          # itemJob.perform_later(current_user.email, @item.id)
          # I want to go to my item show page
          format.html { redirect_to(@item, notice: "item was successfully created !")}
          format.json { render json: @item, status: :created, location: @item }
        else
          format.html { render action: 'new' }
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit    
  	@item = Item.find(params[:id])
  end

  def update
  	@item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to @item #item_path(@item.id)
    else 
      redirect_to edit_item_path(@item.id)
    end    
  end  

  def destroy
    @item = Item.find(params[:id])
    ex_l = @item.id
   	@item.destroy
 	  redirect_to items_path, :notice => "item #{ex_l} deleted"
  end


  def tag
    @tagged = Item.tagged_with(params[:tag_id])
    @tag = params[:tag_id]
  end

# 1. In the terminal, run 'elasticsearch'
# 2. In a separate tab in the terminal, run 'rake searchkick:reindex CLASS=Item'
  def search  
    @index_page = false 
    @item = Item.search(params[:term], fields: ["title", "description"], mispellings: {below: 5})
    if @item.blank?
      @error = "No items found in this search phrase"
      render :index
    else
      render :index
    end
  end

  private

  def item_params
  	params.require(:item).permit(:title, :description, :price_per_day, :user_id, :avatar, :tag_list)
  end

  def set_item
    @item = Item.find(params[:id]) 
  end  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="row">
    <div class="center-block col-md-4" style="float: none; padding-left: 4REM;"> 
<%= form_for @item do |form| %>

<div>
  <%= form.label :title %>
  <%= form.text_field :title, placeholder: "Enter Title", class: "form-control form-control-lg"  %><br>

  <%= form.label :description %>
  <%= form.text_field :description, placeholder: "Describe your good", class: "form-control form-control-lg" %><br>

</div>

<div class="control">
  <%= form.label :price_per_day %><br>
  <%= form.number_field :price_per_day, placeholder: "Enter desired price per day", class: "form-control form-control-lg" %><br>
</div>

<div class="field">
  <%= form.label :upload_image %><br />
  <%= form.file_field :avatar %> <br>
</div>


<div class="submit-field">
    <%= form.submit %>
</div>

<% end %>
<br><%= link_to "Delete this item", item_path(@item), method: :delete %>
</div>
</div>

app/views/items/edit.html.erb
<h2 class="new-item-title">Edit this item</h2>
<div class="edit">

    <%= render 'form' %>


<!--   < % if @item.avatars.present? %>
    < % @item.avatars.each do |a| %> -->
<!--       <img src="< %= a.large.url %>" alt=""> -->
      <!-- <%= link_to "Home", root_path %> -->
      
  </div>

app/views/items/index.html.erb
<% if @index_page %>


<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<script src='//cdn.rawgit.com/googlemaps/js-rich-marker/gh-pages/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

<div id="search_items" class="form-inline">
	<div > <!--class="input-group"-->
		<%= form_tag("/items", method: "get", class:"input-group-addon") do %>
		<%= text_field_tag(:term, params[:term], placeholder:"What are you looking for?" , style: "width: 300px", class: "form-control")%>
		<input id="geo" class="form-control" type="text" placeholder="Where are you looking?" />
		<%= hidden_field_tag(:formatted_address) %>
		<%= hidden_field_tag(:postal_code) %>
		<%= hidden_field_tag(:locality) %>
		<%= hidden_field_tag(:administrative_area_level_1) %>
		<%= hidden_field_tag(:country) %>

		
		<%= label_tag(:range, "Up to:",class:"display: inline") %>
		<%= select_tag("range", "<option>0</option><option>10</option><option>20</option><option>50</option><option>100</option>".html_safe,class:"form-control")%>
		<%= submit_tag("Search", class: 'btn btn-primary') %>
	</div>
		<% end %>
	</div>







<div>
  <div id="search_map" style="overflow: hidden"></div>
</div>
<% end %>
<br>

<div class = "container">
<hgroup class="mb20 fluid-container">
		<h1 class="col-lg-12" style="text-align: center; margin-top: 4.5rem;">Search Results</h1>
		<% if @error.blank? %>
			<h2 class="lead"><strong class="text-danger"><%= @item.count %></strong> results were found for the search for <strong class="text-danger"><%= params[:term] %></strong></h2>			
		<% else %>
			<h2 class="lead"><strong class="text-danger"><%= @error.first %></strong></h2>
		<% end %>					
	</hgroup>


<table class="table table-striped">
  <thead>
    <tr>
      <th style="text-align: center;"><h3>Photo</h3></th>
      <th style="text-align: center;"><h3></h3></th>
      <th style="text-align: center;"><h3>Title</h3></th>
      <th style="text-align: center;"><h3>Description</h3></th>
      <th style="text-align: center;"><h3>Price (MYR)</h3></th>
    </tr>
  </thead>
  <tbody>
<% @item.each do |i|%>
  <tr style="text-align: center;">
    <td><%= link_to image_tag(i.avatar.thumb.url), item_path(i.id) %></td>
        <td><ul class="meta-search">
    					<li><i style="text-align: left;" class="fa fa-location-arrow fa-1"></i> <span><%= i.user.locality if i.user.locality %></span></li>
    					<li><i style="text-align: left;" class="fa fa-tag fa-1"></i> <span><%= i.tag_list.first %></span></li>
    				</ul>
    		</td>
    <td><a href="/items/<%= i.id %>"><h3><%= i.title %></h3></a></td>
    
    <td style="width: 40%;"><p><%= truncate(i.description, length: 160) %></p></td>
    <td><h3>
      <%= i.price_per_day %>
    </h3></td>
  </tr>
<% end %>
</tbody>
</table>
Go to page:  
  <% (1..@nb_pages_needed).each do |page| %>
    <%= link_to page, controller: 'items', action: 'index', page: page %>
  <% end %>
<br><br><br>


<script type="text/javascript">
buildMap(<%=raw @hash.to_json %>)
</script>
</div>

app/views/items/new.html.erb
<h2 class="new-item-title">Rent your stuff !</h2>
<div class="row">
    <div class="center-block col-md-4" style="float: none; padding-left: 11.5REM;">
      
<% if signed_in? %>

<%= form_for @item do |form| %>

  <div><br>
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: "Enter Title", class: "form-control form-control-lg" %>
    <br><br>
    <%= form.label :description %>
    <%= form.text_field :description, placeholder: "Describe your good", class: "form-control form-control-lg"%>

  </div>
  <br><br>
  <div class="control">
    <%= form.label :price_per_day %>
    <%= form.number_field :price_per_day, placeholder: "Enter desired price per day", class: "form-control form-control-lg"%>
  </div>

  <br><br>
  <%= form.label :category %>
  <%= form.select :tag_list, options_for_select(["Kitchen", "Renovation", "Construction", "Tools", "Gardening/Lawncare", "Electronics"]), {}, {:multiple => false, :class => "", :style => "" } %>
  <br><br>

  <div class="field">
    <%= form.label :upload_image %><br>
    <%= form.file_field :avatar %> 
  </div><br>

  <div class="submit-field">
      <%= form.submit %>
  </div>

  <% end %>
<% else %>
	<% flash[:error] = "You need to register or sign in in order to be able to list you item" %>
<% end %>

</div>

</div>

app/views/items/show.html.erb
<div class="container">

<table id="item_table" class="search_items table table-striped">


<h2 class="new-item-title">Item Details</h2>

<table class="search_items table table-striped">

    <tr>
      <th style="text-align: center;">
        <h1><%= @item.title %></h1>
        <%= image_tag (@item.avatar.large.url) %>
      </th>
      <tr>
        <div class="col-md-12">
          <th style="text-align: center;">
            <div class="col-md-4">
              <i class="fa fa-money fa-3 large_fav"></i><span style="font-size: 20px"> MYR<%= @item.price_per_day %></span>
            </div>
            <div class="col-md-4">
              <i class="fa fa-location-arrow fa-3 large_fav"></i><span style="font-size: 20px"><%= @item.user.locality %></span>
            </div>
            <div class="col-md-4">
              <i class="fa fa-tag fa-3 large_fav"></i> <span style="font-size: 20px"><%= @item.tag_list.first %></span>
            </div>
          </th>
        </div>
      <tr>
        <td style="padding-bottom: 100px"><h3><%= @item.description %></h3></td>
</table>

<hr>
<div class="col-md-12" style="padding-top: 20px">
   <div class="col-md-3">
   </div>
   <div class="col-md-4">
      <h3>Rent now from:</h3>
    </div>
    <div class="col-md-4">
      <h2><%= link_to @item.user.first_name, user_path(@item.user.id)%></h2>
      <% if @item.user.avatar.present? %>
        <span>
        <img src="<%= @item.user.avatar.thumb.url %>" class="img-circle" alt="">
        </span>
      <% else %>
        <img class="avatar" src="http://placehold.it/64x64">
      <% end %>
    </div>
    <div class="col-md-4" style="text-align: center;">
    <br>
    <%= link_to "Enquire", new_conversation_path(item_id: @item.id), class: "btn btn-info" %>
    <br>
    <br>
    <%= link_to "Book now", new_item_rental_path(item_id: @item.id), class: "btn btn-success" %>
    </div>
  </div>

</div>




<br>
<br>
<br>
<br>
   <% if @item.user==current_user %>
  <div>
  <%= link_to "Edit", edit_item_path(@item.id), method: :get, class: "btn btn-warning"%>
  <%= link_to "Delete", item_path(@item.id), method: :delete, class: "btn btn-danger"%>
</div>
<% end %>

app/views/items/tag.html.erb
<br>Category: <%= @tag %><br><br>

<% @tagged.each do |t|%>
	<a href="/tags/<%=t.id%>"><%= t.title %></a><br>
	Price: <%= t.price_per_day %><br>
	<% end %>