config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , registrations: "users/registrations", sessions: 'users/sessions'}

  root 'welcome#index'

  resources :users, controller: 'users', only: [:show, :edit, :update, :destroy, :index] 
  
  resources :items do
    resources :rentals, :only => [:create, :new, :show]
  end
  
   get "/items/tags/:tag_id" => "items#tag", as: "tags"
   get '/search', to: 'items#search'

  get "mailboxes/inbox" => "mailboxes#inbox", as: :mailboxes_inbox
  get "mailboxes/sent" => "mailboxes#sent", as: :mailboxes_sent
  get "mailboxes/archive" => "mailboxes#archive", as: :mailboxes_archive

  resources :conversations do
    member do
      post :reply
      post :archive
      post :unarchive
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title>bORO</title>
   <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <%= stylesheet_link_tag 'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'drop-down-menu', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="text/css" href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css'>
  <%= google_webfonts_init({google: ['Comfortaa']}) %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="/manifest.json">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
  <%= favicon_link_tag "favicon.ico" %>
  <script async defer type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB39iSJL86w7qssvZjO0-yd4gYm5c2gpa4&libraries=places"></script> 
  <%= javascript_include_tag 'jquery', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.geocomplete', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'drop-down-menu', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'freewall', 'data-turbolinks-track' => true %>
  <!-- < %= javascript_include_tag 'bootstrap-datepicker', 'data-turbolinks-track' => true %> -->
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'what-input','data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> 
  <script src='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js'></script>
  <script src="https://use.fontawesome.com/61b8a9195a.js"></script>
  <meta name="apple-mobile-web-app-title" content="Boro">
  <meta name="application-name" content="Boro">
  <meta name="theme-color" content="#ffffff">
</head>
<body>
  <!-- Fixed navbar -->
  <!-- TEMPLATE -->
<div id="custom-bootstrap-menu" class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid row">
        <div class="navbar-header col-xs-12">
          <a id="logo" class="navbar-brand col-xs-10" href="/"><span>b</span><span>o</span><span>r</span><span>o</span></a>
            <button type="button" class="navbar-toggle col-xs-2" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse navbar-menubuilder">
            <ul class="nav navbar-nav navbar-left">

              <li>
                  <%= form_tag("/items", method: "get", class:"input-group-addon") do %>
                  <%= text_field_tag(:term, params[:term], placeholder:"What are you looking for?", class: "form-control",id:"mainsearch")%>
                  <input id="geo" class="form-control" type="text" placeholder="Where are you looking?" />
                  <%= hidden_field_tag(:formatted_address) %>
                  <%= hidden_field_tag(:postal_code) %>
                  <%= hidden_field_tag(:locality) %>
                  <%= hidden_field_tag(:administrative_area_level_1) %>
                  <%= hidden_field_tag(:country) %>
    
                  <%= submit_tag("Search", class: 'btn btn-primary', id:"submit_1" ) %>
                  <% end %> 



                <li><a class="btn" href="/items">Local Rentables</a>
                </li>
                <li><a class="btn" href="/users">Users in the <span>b</span><span>o</span><span>r</span><span>o</span></a>
                </li>
                <li><a class="btn" href="/items/new">Rent Your Things!</a>
                </li>
<!--                 <li><a href="/contact">Contact Us</a>
                </li> -->
              <% if signed_in? %>
              <li class="dropdown">
                <% if current_user.avatar.present? %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag current_user.avatar.thumb.url, :class => "img-circle profile_pic" %>
                </a>
                <%else%>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <img class="img-circle profile_pic" src="https://placeholdit.imgix.net/~text?txtsize=8&txt=64%C3%9764&w=64&h=64" alt="">
                </a>
                <%end%>
                <ul id="dd" class="dropdown-menu">
                  <li>
                    <%= link_to "Messages", mailboxes_inbox_path %>
                    <span class="label label-danger message_block"><%=unread_messages_count%></span>
                  </li>
                  <li><%= link_to "Rental History", user_path(current_user)%></li>
                  <li><%= link_to "Edit Profile", edit_user_registration_path(current_user)%></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
                </ul>
              </li> 
              <% else %>             
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <img class="img-circle profile_pic" src="https://placeholdit.imgix.net/~text?txtsize=8&txt=64%C3%9764&w=64&h=64" alt="">
                </a>              
                <ul class="dropdown-menu">
                  <li style="color: white;"><a href="/users/sign_up">Sign Up</a></li>
                  <li style="color: white;"><a href="/users/sign_in">Log In</a></li>
                  <li style="color: white;"><a href="/users/auth/facebook">Login with Facebook</a></li>
                </ul>
              </li>
              <% end %>
            </ul>
        </div>
    </div>
</div>

<!-- FIN TEPLATYE -->
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

  <%= yield %>

  <!-- GOOGLE MAPS STATIC -->

<script>
  function initMap() {
    var petaling = {lat: 3.134717, lng: 101.629968};  
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 12,
      center: petaling, 
      styles: [{"featureType":"administrative","elementType":"labels.text.fill","stylers":[{"color":"#444444"}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#f2f2f2"}]},{"featureType":"poi","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"all","stylers":[{"saturation":-100},{"lightness":45}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#46bcec"},{"visibility":"on"}]}]
    });
    var marker = new google.maps.Marker({
      position: petaling,
      map: map
    });
  }

// FREEWALL SCRIPT

// put Rails variable in JQuery ?
    var temp = "<div class='brick' style='width:{width}px;'><img src='/items/item{index}.jpg' width='100%'></div>";
    var w = 1, h = 1, html = '', limitItem = 29; // limitItem = Items.all.count in Ruby
    for (var i = 0; i < limitItem; ++i) {
      w = 1 + 3 * Math.random() << 0;
      html += temp.replace(/\{width\}/g, w*150).replace("{index}", i + 1);
    }
    $("#freewall").html(html);

    var wall = new Freewall("#freewall");
    wall.reset({
      selector: '.brick',
      animate: true,
      cellW: 150,
      cellH: 'auto',
      onResize: function() {
        wall.fitWidth();
      }
    });


    var images = wall.container.find('.brick');
    images.find('img').load(function() {
      wall.fitWidth();
    }); 


  //  GOOGLE MAPS TEST BEGIN 

      function initMap() {
        var petaling = {lat: 3.134717, lng: 101.629968};  
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: petaling
        });
        var marker = new google.maps.Marker({
          position: petaling,
          map: map
        });
      }
    </script>
 <!-- GOOGLE MAPS TEST END -->    
 <!-- GEOCOMPLETE START-->
  <script>
      $(function(){
        $("#geocomplete").geocomplete({
          map: ".map_canvas",
          details: "form",
          types: ["geocode", "establishment"],
          location: "Kuala Lumpur",
        });

        $("#find").click(function(){
          $("#geocomplete").trigger("geocode");
        });

        var userlocation = $("#editloc").val()
        $("#geoedit").geocomplete({
          map: ".map_canvas",
          details: "form",
          types: ["geocode", "establishment"],
          location: userlocation,
        });

        $("#editfind").click(function(){
          $("#geocomplete").trigger("geocode");
        });

      

        $(".brick").click(
      function(){
        $(this).fadeToggle(1000);
      });

        $("#geo").geocomplete({
          details: "form",
          types: ["geocode", "establishment"],
        });
      });
    </script>

 <!-- GEOCOMPLETE END -->
<script>
  $("#custom-bootstrap-menu > div > div.navbar-header.col-xs-12 > button").click(function(){
    $(this).toggleClass("collapse");
    });
</script>

</body>
</html>

app/views/layouts/application.html.slim
#custom-bootstrap-menu.navbar.navbar-default role="navigation" 
  .container-fluid
    .navbar-header
      a.navbar-brand href="#"  Brand
      button.navbar-toggle data-target=".navbar-menubuilder" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
    .collapse.navbar-collapse.navbar-menubuilder
      ul.nav.navbar-nav.navbar-left
        li
          a href="/"  Home
        li
          a href="/products"  Products
        li
          a href="/about-us"  About Us
        li
          a href="/contact"  Contact Us

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>
<head>
   <title>bORO</title>
  <%= stylesheet_link_tag 'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'drop-down-menu', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'data-turbolinks-track' => true %>
  <%= google_webfonts_init({google: ['Comfortaa','Open Sans']}) %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="/manifest.json">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
  <%= favicon_link_tag "favicon.ico" %>
  <%= javascript_include_tag 'jquery', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.geocomplete', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'drop-down-menu', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'freewall', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap-datepicker', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'what-input','data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> 
  <script src="https://use.fontawesome.com/61b8a9195a.js"></script>
  <meta name="apple-mobile-web-app-title" content="Boro">
  <meta name="application-name" content="Boro">
  <meta name="theme-color" content="#ffffff">
  <script async defer type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB39iSJL86w7qssvZjO0-yd4gYm5c2gpa4&libraries=places&callback=initMap&callback=buildMap"></script> 

</head>
<body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        
        <!-- Added data-* and aria into #navbar -->
        <div id="navbar" class="navbar-collapse collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <ul class="nav navbar-nav">
            <div class="nav navbar-nav navbar-left">
              <li><a id="logo" class="navbar-brand" href="/">
                <span>b</span><span>o</span><span>r</span><span>o</span></a>
              </li>
            </div>

            <li><%= form_for Item.new, method: :get, url: search_path, class: "navbar-form navbar-left" do |f| %>
            <%= text_field_tag :term, params[:term], placeholder:"What are you looking for?" %>
            <%= f.submit 'search', class: 'btn btn-primary' %>
            <% end %>
              
            </li>

<!--           <form class="new_item input-group" id="new_item" action="/search" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓">
          <input class="form-control" type="text" name="term" id="term" placeholder="What are you looking for?">
          <span class="input-group-btn"><input type="submit" name="commit" value="search" class="btn btn-primary btn btn-default"></span>
          </form> -->


          <div id="navright" class="nav navbar-nav navbar-right"> 
            <li><a class="btn" href="/items">Local Rentables</a></li> 
            <li><a class="btn" href="/users">Users Around Me</a></li> 
            <li><a class="btn" href="/items/new">Rent Your Things!</a></li> 

            <% if signed_in? %>
             <!-- DROPDOWN MENU BELOW -->
            <li class="dropdown">

            <% if current_user.avatar.present? %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag current_user.avatar.thumb.url, :class => "profile_pic" %><span class="caret"></span></a>
              <%else%>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile<span class="caret"></span></a>
              <%end%>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path(current_user)%></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
              </ul>
            </li>
              <% else %>
            <li><a href="/users/sign_up">Sign Up</a></li>
            <li><a href="/users/sign_in">Log In</a></li>
            <% end %>
            
            </div>
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>
<div class="container">
  <%= yield %>
</div>


<p><a href="/users/sign_up">Sign Up</a></p>

  <!-- GOOGLE MAPS STATIC -->

<script>
  function initMap() {
    var petaling = {lat: 3.134717, lng: 101.629968};  
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 12,
      center: petaling, 
      styles: [{"featureType":"administrative","elementType":"labels.text.fill","stylers":[{"color":"#444444"}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#f2f2f2"}]},{"featureType":"poi","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"all","stylers":[{"saturation":-100},{"lightness":45}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#46bcec"},{"visibility":"on"}]}]
    });
    var marker = new google.maps.Marker({
      position: petaling,
      map: map
    });
  }

// FREEWALL SCRIPT

// put Rails variable in JQuery ?
    var temp = "<div class='brick' style='width:{width}px;'><img src='/items/item{index}.jpg' width='100%'></div>";
    var w = 1, h = 1, html = '', limitItem = 29; // limitItem = Items.all.count in Ruby
    for (var i = 0; i < limitItem; ++i) {
      w = 1 + 3 * Math.random() << 0;
      html += temp.replace(/\{width\}/g, w*150).replace("{index}", i + 1);
    }
    $("#freewall").html(html);

    var wall = new Freewall("#freewall");
    wall.reset({
      selector: '.brick',
      animate: true,
      cellW: 150,
      cellH: 'auto',
      onResize: function() {
        wall.fitWidth();
      }
    });


    var images = wall.container.find('.brick');
    images.find('img').load(function() {
      wall.fitWidth();
    }); 


  //  GOOGLE MAPS TEST BEGIN 

      function initMap() {
        var petaling = {lat: 3.134717, lng: 101.629968};  
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: petaling
        });
        var marker = new google.maps.Marker({
          position: petaling,
          map: map
        });
      }
    </script>
 <!-- GOOGLE MAPS TEST END -->    
 <!-- GEOCOMPLETE START-->
  <script>
      $(function(){


        $("#geocomplete").geocomplete({
          map: ".map_canvas",
          details: "form",
          types: ["geocode", "establishment"],
          location: "Kuala Lumpur",
        });

        $("#find").click(function(){
          $("#geocomplete").trigger("geocode");
        });

        var userlocation = $("#editloc").val()
        $("#geoedit").geocomplete({
          map: ".map_canvas",
          details: "form",
          types: ["geocode", "establishment"],
          location: userlocation,
        });

        $("#editfind").click(function(){
          $("#geocomplete").trigger("geocode");
        });

      

        $(".brick").click(
      function(){
        $(this).fadeToggle(1000);
      });

        $("#geo").geocomplete({
          details: "form",
          types: ["geocode", "establishment"],
        });
      });
    </script>

 <!-- GEOCOMPLETE END -->
</body>
</html>